Document: elfio
Title: Debian elfio Manual
Author: <insert document author here>
Abstract: This manual describes what elfio is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/elfio/elfio.sgml.gz

Format: postscript
Files: /usr/share/doc/elfio/elfio.ps.gz

Format: text
Files: /usr/share/doc/elfio/elfio.text.gz

Format: HTML
Index: /usr/share/doc/elfio/html/index.html
Files: /usr/share/doc/elfio/html/*.html
